# -*- coding: utf-8 -*-
"""ML1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r97THm8EuDE3v_GmEsWCctVR_F9xZF1Y
"""



"""Addition

"""

a=10
b=5
c=a+b
print(c)